[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Mike Nichols <mike.nichols@temporal.io>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

